server:
  servlet:
    context-path: /taw
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: postgres
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: false
    out-of-order: false
#  freemarker:
#    allow-request-override: false
#    allow-session-override: false
#    cache: true
#    charset: UTF-8
#    check-template-location: true
#    content-type: text/html
#    enabled: true
#    expose-request-attributes: false
#    expose-session-attributes: false
#    expose-spring-macro-helpers: true
#    prefer-file-system-access: true
#    suffix: .ftl
#    template-loader-path: classpath:/templates/

ignore:
  urls:
    - /resources/**