server:
  servlet:
    context-path: /accounts
  port: 8082

security:
  oauth2:
    client:
      clientId: taw-account
      clientSecret: 1234
      accessTokenUri: http://localhost:8081/taw/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://localhost:8080/taw/user/current
      token-info-uri: http://localhost:8080/taw/oauth/check_token

feign:
  hystrix:
    enabled: true